### ISSUE TITLE
When I tried to install from NPM it gave me lots of errors

### ISSUE THREAD

**Issue by LinkTree3** [derhuerst/time-tracking#2]
When I tried to install from NPM it gave me lots of errors.
I had to download the repository and manually install the new package.
is the npm package not updated? when trying to debug it I noticed it is using "bluebird" as the promises library but in this version it is using "mkdirp-then" instead.

**Comment by derhuerst** [comment]
I didn't push an NPM package recently. Will do today.

> when trying to debug it I noticed it is using "bluebird" as the promises library but in this version it is using "mkdirp-then" instead.

I'm not exactly sure what you mean. `bluebird` and `mkdirp-then` can be used together, since `bluebird` has a native-Promises-compatible API. But on `HEAD`, I got rid of `bluebird` anyway.

**Comment by derhuerst** [comment]
> When I tried to install from NPM it gave me lots of errors.

Should be fixed on `HEAD` now, please try.

**Comment by LinkTree3** [comment]
Same Issues when trying to install from NPM.

**Comment by derhuerst** [comment]
> Same Issues when trying to install from NPM.

What about installing from `HEAD`?

Installing from npm still throws errors because i didn't publish the a new version yet. (;

**Comment by derhuerst** [comment]
I released `time-tracking@0.4.0`. Should be better now.
