### ISSUE TITLE
No right triangle in windows 7

### ISSUE THREAD

**Issue by LinkTree3** [derhuerst/time-tracking#3]
I don't know why but \u25b6 doesn't return the triangle for me. I see an empty square or a question mark instead.
I tried it in windows cmd/cmder/cygwin mintty.
I got a question mark In windows cmd.

**Comment by derhuerst** [comment]
Don't know about the exact problem, but using [sindresorhus/figures](https://github.com/sindresorhus/figures/blob/f50c12f585c8d64ebe5f7d42f711ee38ba9765c5/index.js#L10) might be a solution.

**Comment by derhuerst** [comment]
Did 52beca0 fix the problem? If it did, I will push to NPM.

**Comment by LinkTree3** [comment]
replacing `\u25b6` with `\u52beca0` gave me `劾a0`.

 sindresorhus/figures doesn't have the triangle symbol. :(

**Comment by derhuerst** [comment]
> sindresorhus/figures doesn't have the triangle symbol. :(

Consider a pull request if you have a proper windows equivalent. (;

I used [the `pointer` icon](https://github.com/sindresorhus/figures/blob/f50c12f585c8d64ebe5f7d42f711ee38ba9765c5/index.js#L23).

**Comment by LinkTree3** [comment]
I used the [`arrowRight` Icon](https://github.com/sindresorhus/figures/blob/f50c12f585c8d64ebe5f7d42f711ee38ba9765c5/index.js#L34) as it is seems to be supported everywhere.

**Comment by LinkTree3** [comment]
I checked the charmap on windows and found this one ►`'\u25ba'` :)

**Comment by derhuerst** [comment]
Could you check support for [the "black right-pointing triangle" character](http://www.fileformat.info/info/unicode/char/25b6/index.htm) on your system? This might be a valuable addition to sindresorhus/figures.

**Comment by LinkTree3** [comment]
I see it in chrome/firefox. It seems to just not show in console applications.

**Comment by derhuerst** [comment]
Can you find any fallback characters?

**Comment by LinkTree3** [comment]
Yea as I mentioned above I found and used this one ► `'\u25ba'`.
It works great. ;D

**Comment by derhuerst** [comment]
Would you mind to submit a pull request to sindresorhus/figures with `'\u25b6'` (▶) and `'\u25ba'` (►) as fallback?

**Comment by LinkTree3** [comment]
Yes I will do it. :)

**Comment by derhuerst** [comment]
Also, I thought about using a `'\u23f8'` (⏸) instead of the stop icon. Is it supported? This might be a valuable PR as well…

**Comment by LinkTree3** [comment]
It seems the [sindresorhus/figures](https://github.com/sindresorhus/figures) repository doesn't accept new pull requests. It keeps saying I have no permission. I am new to git though so I might be doing something wrong.
`'\u23f8'` looks like a long rectangle instead of a square. I personally like the filled in square you have currently.

**Comment by derhuerst** [comment]
> It seems the sindresorhus/figures repository doesn't accept new pull requests. It keeps saying I have no permission. I am new to git though so I might be doing something wrong.

See [_using pull requests_](https://help.github.com/articles/using-pull-requests/).

> '\u23f8' looks like a long rectangle instead of a square.

Hm, does any other Unicode char from the same block work? I don't have a Windows machine to test unfortunately.

**Comment by derhuerst** [comment]
@LinkTree3 

> Also, I thought about using a '\u23f8' (⏸) instead of the stop icon. Is it supported? This might be a valuable PR as well…

Did you create a PR? If not, I'd do it.

Edit: created a PR for ▶/►.

**Comment by LinkTree3** [comment]
Lol I just created one too. I forgot you had to fork the repository first before you can make pull requests.

**Comment by derhuerst** [comment]
I released `time-tracking@0.4.0` with a [play symbol](https://github.com/derhuerst/figures/blob/play-symbol/index.js#L11). Have a look!
